import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "./Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Abhi's News Portal</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  );
};

export default Home;
