import type { NextPage } from "next";
import Head from "next/head";
import Header from "./Header";
import Homepage from "./Homepage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Abhi's News Portal</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* add -  dark:bg-zinc-900 */}
      <body className="bg-gray-200 dark:bg-zinc-900  h-full  transition-all duration-700">
        <Header />
        <Homepage />
      </body>
    </>
  );
};

export default Home;
